### ISSUE TITLE
Decorator examples don't work

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#193]
## Bug Report

Decorators need some help.

**Comment by Mahi** [comment]
Just curious, is there any need for the decorators in the first place? I mean, is there any advantage over just using the `Window` class?

**Comment by pvcraven** [comment]
Some people prefer a more functional-based approach, rather than classes.

Unfortunately I'm not great at writing decorators yet, so that's something I hope to work on.

**Comment by Mahi** [comment]
Right, I believe I could help with that. What is the desired API, you wish to keep the `arcade.decorator.something` like this:
```python
@arcade.decorator.setup
def setup_game(window):
    do_stuff()
```
And is there a reason it's all in a class rather than a module called `decorator` (in which case the syntax would be the same), do you intent this to support subclassing or something?

**Comment by Mahi** [comment]
Sure, no rush :)

Yet another idea I came up with is to use a window object with decorators rather than subclassing:
```python
window = arcade.Window(...)

@window.on_setup  # or window.decorator.setup or so
def setup_game():
    do_stuff(window)

@window.on_update
def update_game(delta_time):
    more_stuff(window)

arcade.run()
```
I feel like this is the best solution, but I'm not sure yet

**Comment by Mahi** [comment]
The last version would be as simple as adding decorators to the `arcade.application.Window` class:
```python
class Window(pyglet.window.Window):
    ...
    def on_update(self, callback):
        self.update = callback  # Override Window.update with instance attribute
        return callback

window = Window(...)

@window.on_update
def update(delta_time):
    window.do_stuff(delta_time)
```

**Comment by pvcraven** [comment]
I'm kind of hoping to sit and spend some time thinking though this over the summer. I'm not much of a decorator expert, but hopefully with some time I can examine what Pyglet has done and learn more. Then come up with several examples to help prove it out.

**Comment by pauleveritt** [comment]
@Mahi I had a big branch last year where I did some experiments. [Here's a prototype](https://github.com/pauleveritt/arcade_decorator). Too ambitious though, I was trying to solve multiple problems at once. I'm still attracted though to the ideas you're discussing.

First, I was trying to get rid of a global window and have the decorator support implicitly create a window, store it inside the decorator, and pass into functions. I wanted a better test writing experience and not have a global window.

Second, and the beginning of the too-ambitious...I was trying to craft a "Game API" that let us sit in between pyglet and a user's game and simplify some things. We are currently bound by pyglet's contract. I'd still like @game.on_update or even @game.some_other_method_completely but I think @pvcraven rightfully wants evolution not revolution.

**Comment by Mahi** [comment]
I've had a look at pyglet since I last posted here, and it seems like pyglet *already* has a support for both [multiple windows](https://pyglet.readthedocs.io/en/pyglet-1.2-maintenance/api/pyglet/pyglet.window.html#working-with-multiple-screens) *and* [decorators for registering handlers](https://pyglet.readthedocs.io/en/pyglet-1.2-maintenance/api/pyglet/pyglet.window.html#getting-started). To me it looks like `arcade` has explicitly created a limitation of using only one window in the [`window_commands.py`](https://github.com/pvcraven/arcade/blob/master/arcade/window_commands.py#L23) file, so I'd start off by getting rid of this limitation.

**Comment by Mahi** [comment]
@pauleveritt What I'm saying is that `pyglet` supports multiple windows, and `arcade` uses `pyglet` for its windowing, so `arcade` should support multiple windows. But it doesn't, because the window_commands.py file has explicitly defined a single global window instance. If we get rid of using this global instance, we automatically inherit the multi-window-support from `pyglet`.

**Comment by pvcraven** [comment]
This was debated when I started Arcade. Short answer, using a global keeps the user from having to pass around the window context to every drawing command and everything else. Keeping things simple and easy is an important part of this library. This simplifies the 99.9% (or whatever) of programs that run on one window. It forces multi-window programs to use something else. At this point, I'm ok with that decision.

**Comment by Mahi** [comment]
> using a global keeps the user from having to pass around the window context to every drawing command and everything else.

I believe pyglet already takes care of this, it has its own internal global window, which can be changed with the [Window.switch_to](http://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/modules/window.html#pyglet.window.Window.switch_to) function. So literally none of the commands would change if we got rid of the global instance.
