### ISSUE TITLE
PyInstaller example doesn't work if there is a space in the python path

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#239]
The new PyInstaller example at: https://github.com/pvcraven/arcade/tree/master/arcade/examples/pyinstaller

If python is stored in a path like "Program Files" then it doesn't handle the space appropriately and python path is "Program" and everything fails.

**Comment by pvcraven** [comment]
I tried creating a python version of `build-exe.bat`. That got around the space issue, and made things a bit more pythonic. But the resulting exe doesn't work.

**Comment by pvcraven** [comment]
See https://github.com/pvcraven/arcade/blob/master/arcade/examples/pyinstaller/build-exe.py

**Comment by pvcraven** [comment]
Closing.

**Comment by LauLauThom** [comment]
> The new PyInstaller example at: https://github.com/pvcraven/arcade/tree/master/arcade/examples/pyinstaller
> 
> If python is stored in a path like "Program Files" then it doesn't handle the space appropriately and python path is "Program" and everything fails.

Hi, sorry to revive an old issue.
I have a similar issue, I can compile an exe but when I try to run the exe, I have some import issues (ex : numpy.f2py) that are not resolved by specifying the `hidden-import` flag.
Looking at the output of the compilation process I am quite sure the blank space is the reason pyinstaller cannot find some stuff from the python installation (here missing the python310.zip, DLLs and lib subdirectories).
I installed python via the windows app store.

``` 
1679 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\admin\\Documents\\GitHub\\light-sheet-alignment\\alignment_env\\Scripts\\pyinstaller.exe',
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\python310.zip',
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\DLLs',
 'C:\\Program '
 'Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib',
```

Is there a way to have pyinstaller not cut at the space, I tried putting the path by hand in the spec files but that did not help.
I also tried WindowsPowershell instead of the default command prompt but no success neither.

I guess I will resolve to installing another python installation in a directory without spaces.
