### ISSUE TITLE
arcade.read_tiled_map() not checking for data encoding

### ISSUE THREAD

**Issue by MushroomMaula** [pvcraven/arcade#251]
### Actual behavior:
Trying to read a tiled map where data is stored in CSV it throws error because its expecting base64 zlib compressed data
### Expected behavior:
`read_tiled_map()` should check for the encoding in the xml and read according to that
## Documentation request:
Include example `.tmx` and `.tsx` files in the tiled map examples

**Comment by MushroomMaula** [comment]
I would like to work on this issue

**Comment by bjorn** [comment]
Since there are many different formats (csv, xml, base64, with or without compression (zlib or gzip)) and possibly more in the future, I'll just add that in general I do not expect each game or library to support all of them. Of course, libraries should throw proper errors when the format is not supported and document which formats are supported.

All those formats were mostly added because different people have different needs, but in practice it has mostly added a burden on developers of frameworks and libraries supporting Tiled maps. :/

**Comment by pvcraven** [comment]
Closed with 2.0 release.
