### ISSUE TITLE
Create example showing how to manage multiple windows

### ISSUE THREAD

**Issue by ReblochonMasque** [pvcraven/arcade#345]
Is there support for several windows/surfaces opened simultaneously?  
Where can I find examples, or tutorial?

**Comment by pvcraven** [comment]
No examples yet. (I'd be happy to have some!) There is a `setWindow` and `getWindow` command that lets you flip between the windows for the drawing commands.

**Comment by ReblochonMasque** [comment]
Thank you.

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by einarf** [comment]
You can open and close, then open a new window at the very least. We don't really have support for multiple windows in arcade because this would add so much complexity. We also cannot guaratnee cross platform support. Remember we need to cover windows, linux and macos here. When we add OpenGL ES on top of that for various enviroments it's not getting any less ugly.

I would engourage keeping things inside the same window. Viewports can be used if needed. Pyglet 2.0 also have issues with this. It's not an easy problem to solve.
