### ISSUE TITLE
Add ability to specify a point the sprite rotates around

### ISSUE THREAD

**Issue by Ace5273** [pvcraven/arcade#380]
## Enhancement request:
Add rotation point
### What should be added/changed?
A point which the sprite will rotate from
### What would it help with?
fluid animation

**Comment by pvcraven** [comment]
This enhancement is not currently in process. Please re-open if you'd like to work on it. A full list of desired enhancements is available at:

http://arcade.academy/enhancement_list.html

**Comment by humansHS** [comment]
So I am planning on implementing this functionality for my own use, figured I might as well help grow Arcade by adding it to the code base!

It seems like a simple enough system to implement, since rotating a sprite around a point will be the same as changing its angle except it also move the position too:

![rotation_point](https://user-images.githubusercontent.com/57516846/73827281-29da2580-484f-11ea-911d-f71833e61a13.png)

Please correct me if I am wrong. As far as I can tell just need to add/change the following functions of Sprite class:

rotation_point (tuple): The point which the sprite will rotate from, default is position.

```
def _get_rotation_point # Will need to be created, easy.
def _set_rotation_point # Will need to be created, easy.

def _set_angle  # Needs to have functionality added:
                # Will need to check for a rotation_point, if so, then runs
                # rotate_point on position and rotation_point and then
                # _set_position using the results
```

I'll get right on the next steps of:
http://arcade.academy/how_to_submit_changes.html#how-to-submit-changes

But I am not sure how to re-open an Issue, if this gets no attention then I will open a new Issue and link to this one.

Thanks!

**Comment by pvcraven** [comment]
Hey thanks! I think you have a right idea. I reopened the issue and assigned it to you. Please make a PR if you can. Let me know if you have questions.

**Comment by humansHS** [comment]
I have created a pull request and added the code. There are several things I am not quite sure about that could do with someone more experienced double checking :)

**Comment by pvcraven** [comment]
This is on the enhancement list. It can be reopened if someone is actively working on it. As noted from the PR, this is more complex than originally thought.

**Comment by einarf** [comment]
We've  added examples for this now. It could eventually be moved into the Sprite class. Another possibility is adding support in the shader itself. This will however add a lot more complexity for collision detection and spatial hashing.
