### ISSUE TITLE
Travis CI Linux jobs are failing

### ISSUE THREAD

**Issue by cclauss** [pvcraven/arcade#456]
https://travis-ci.org/pvcraven/arcade/jobs/570900860#L520

Should these jobs fail in a hadless environment?  __tests/unit/test_view.py FFF__

**Comment by pvcraven** [comment]
Most of the unit tests require building a window. Not only that, they require OpenGL support on that window.

There needs to be sorting of the mocked tests, and the non-mocked tests. tests/unit were supposed to be mocked, and /tests/unit2 the non-mocked ones. As you can see, that's not really sorted right.

**Comment by cclauss** [comment]
https://docs.travis-ci.com/user/gui-and-headless-browsers says nothing about OpenGL.  Do we need to add a atp-get library?

**Comment by SirGnip** [comment]
`test_view.py` was just added a couple days ago.  It creates a `Window` object, but does not show it.

I'm not very familiar with arcade's CI jobs and the context in which the tests run.  But, looking at the failure link above, it looks like an OpenGL related failure.  So, I'm guessing OpenGL is simply not available on Travis CI, even if no windows are drawn?

I'll take a look at how to stub/mock out the `Window` object in these tests so that it can run headless.  But, in the meantime, it sounds like the test should be moved in `/tests/unit2`?

**Comment by pvcraven** [comment]
Yes, if it needs a display it should be in unit2.

And I don't think TravisCI support OpenGL 3.3+, so we have to skip tests that require a display.

**Comment by SirGnip** [comment]
If this is blocking your work, feel free to move `test_view.py` to `/tests/unit2`.  Otherwise, I'll move it when I get a chance and then see about mocking out these tests to not require OpenGL.
