### ISSUE TITLE
MacOS not getting default font

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#488]
## Bug Report

Report via e-mail that Mac wasn't showing text.

Additional info: "I think I figured out the issue.  I'm running Mac OSX (El Capitan) and the default fonts you have for draw_text are 'calibri' and 'arial'.  Calibri isn't by default installed on Max OSX at all and Arial is, but it's capitalized.  So if I explicitly call 'Arial' it works or if I try another Mac default font like 'Verdana' it works.  Not sure if others have had this issue either, I didn't find anything about it when Googling.  Apologies if I missed this in the documentation. Thanks so much for the reply!"

**Comment by pvcraven** [comment]
Current list of default fonts. Need a full path/name for what will fix this on the Mac:
``` python
            font_names = ("arial.ttf",
                          'NotoSans-Regular.ttf',
                          "/usr/share/fonts/truetype/freefont/FreeMono.ttf",
                          '/System/Library/Fonts/SFNSDisplay.ttf')
```

**Comment by TheCodeSummoner** [comment]
I will have a look tomorrow when I have access to my macOS machine.

**Comment by jotagarciaz** [comment]
Probably this problem is also happening in other versions of macOS like the newest one "MacOS Catalina". 

I thought it was the O.S. because my program was basically the example of how to create a Text Button of the arcade documentation (http://arcade.academy/examples/gui_text_button.html?highlight=button)  so I tried my code on a "MacOS Mojave" version and it automatically worked.

Although my bug seems a little different from this one in the sense that in my version of the problem the text was showed but in a ridiculous little font size.

**Comment by TheCodeSummoner** [comment]
On `Mac OS X, 10.14.6` the directory is at `/Library/Fonts`, for example `/Library/Fonts/Arial.ttf`.

Complete list at https://en.wikipedia.org/wiki/List_of_typefaces_included_with_macOS

**Comment by pvcraven** [comment]
I just pushed version 2.1.5. Please try it and see if it fixes the issue.

**Comment by jotagarciaz** [comment]
> I just pushed version 2.1.5. Please try it and see if it fixes the issue.

I can try it on Saturday.

**Comment by jotagarciaz** [comment]
The fonts works on Catalina now.
I tried it on a clean installation in my external HDD and my code worked gorgeously, the app runs much better than in my working O.S. which is Mojave.

I don't know the explanation to this phenomenon, but this issue is solve.

**Comment by pvcraven** [comment]
Thanks!!!
