### ISSUE TITLE
Sprite rotate around a point yeilding unexpected results.

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/arcade#589]
Ok, doing some unit tests on this code.

If I do this:
self.character_sprite.set_rotation_point((1, 0))

...with an initial center_x, center_y of (300, 50) I get (-49, 299) as a result. I feel like the correct result should be (301, 49).

**Comment by humansHS** [comment]
What is the rotation of the sprite?

I'll do some testing, but that is likely one of two possible issues:
a) The rotation that is passed into rotate_point needs to have negative sign (most likely).
b) The sprite.center_x/y and rotation_point x/y have been passed into rotate_point incorrectly.

**Comment by pvcraven** [comment]
See around line 64:
https://github.com/pvcraven/arcade/blob/master/tests/unit2/test_sprite.py#L64

**Comment by humansHS** [comment]
I believe I may be a moron. In _set_angle when it applies the center translation:

```
            rotate_x, rotate_y = self.rotation_point
            if rotate_x or rotate_y:
                sprite_rotate = rotate_point(self.center_x, self.center_y,
                                             rotate_x, rotate_y, new_value)
                self.set_position(sprite_rotate[0],sprite_rotate[1])
```

It is setting the rotation point as a an absolute POINT not an offset, I think this was because I originally thought I would set a static point not an offset. But for my personal implementation I wanted an offset point but forgot to apply the change to the code! The change should be simple:

```
            rotate_x, rotate_y = self.rotation_point
            if rotate_x or rotate_y:
                rotate_x += self.center_x
                rotate_y += self.center_y
                sprite_rotate = rotate_point(self.center_x, self.center_y,
                                             rotate_x, rotate_y, new_value)
                self.set_position(sprite_rotate[0],sprite_rotate[1])
```

I will create a pull request ASAP.

A couple of other things:

1) When I put in new code should I also be updating the tests to include unit tests? Is this explained somewhere in the 'contributing' instructions and I skimmed over it?

2) I assume I have done the get and set methods correctly since it appears you have not changed them. My impression is that I only need to do _get or _set when there is extra code to run when changing a property. BUT if that is correct, I believe _set is the option to be used and it is missing some code whereby it should run _set_angle whenever the rotation_point is changed because if it has a non-zero angle of rotation and the rotation_point changes then it will have a new position.

**Comment by humansHS** [comment]
Wait, my solution is still wrong...

**Comment by humansHS** [comment]
Sorry for the wall of text and the incorrect first attempt, I am new to GitHub and working on shared code projects in general!

Technically the code was correct, but the description was incorrect. Absolute sprite rotation point appears to work perfectly. But, since adding enhancements is the intention, I have also implemented relative sprite rotation point. I changed to _get and _set and, _set now applies new rotations when changing rotation_point.

Now, there are two (that I can think of) ways to implement this. My current implementation tries to slow down regular non-relative sprite movement/rotation as little as possible.

But it is about a hundred times slower than the second method if all your sprites are constantly calculating relative rotation. I used the second method for my personal code since I have a specific sprite that I know will constantly be relatively rotating. It may be worth considering a new class (like AnimatedSprite, so maybe RelativeSprite???) that has the optimised code.

![rotation_point](https://user-images.githubusercontent.com/57516846/74096049-7b352e00-4b49-11ea-809d-3173ef4e7023.png)

**First method:** When rotating relatively to a sprite that has already been rotated, the offset (blue square) can not be directly applied to the current sprite centre, it will be incorrect (purple square). So, we first have to rotate the offset by the previous angle. Then we can rotate the sprite center by the difference between the previous angle and the new angle.

**Second method:** We have to always store an absolute sprite center that is updated whenever the sprite is moved through _set_center_x/y by the change of position, but is NOT changed when we change the center when relatively rotating. Then, whenever we relatively rotate, we apply rotate_point to the absolute sprite center (not the actual sprite center).

**Comment by pvcraven** [comment]
Relative rotation seems to be ok. I don't understand what's happening with the other. 

See this example:
https://github.com/pvcraven/arcade/blob/master/arcade/examples/sprite_rotation.py

The third example, I set the rotation center to be where the coin is already. I'd expect it to rotate in-place. It does if I select (0, 0) though. If I select (10, 0) it scoots off weird.

**Comment by humansHS** [comment]
Yeh yep that is my bad again! Line 597:

```
                rotate_x += self_x
                rotate_y += self_y
                if old_angle:
```

Should be:

```
                if old_angle:
                    rotate_x += self_x
                    rotate_y += self_y
```

I think that should solve the issue, it was adding the center location to the absolute rotate_point, which it should not do!

Fixed it and created pull request. Glad relative is working though :dancer:

**Comment by pvcraven** [comment]
Better, but still acts weird. Rotates slow, then super fast, then slow.

**Comment by humansHS** [comment]
So it is rotating around the right point but not by the correct angle?

**Comment by pvcraven** [comment]
https://youtu.be/rNqCxrY94q0

**Comment by humansHS** [comment]
Ok that is definitely not expected behaviour. I will take a closer look later on and make a fix.

On a related note, I would also like to make a minor change to rotate_point:

```
    # now apply rotation
    rotated_x = temp_x * math.cos(math.radians(angle)) - temp_y * math.sin(math.radians(angle))
    rotated_y = temp_x * math.sin(math.radians(angle)) + temp_y * math.cos(math.radians(angle))
```
to:
```
    # now apply rotation
    angle = math.radians(angle)
    rotated_x = temp_x * math.cos(angle) - temp_y * math.sin(angle)
    rotated_y = temp_x * math.sin(angle) + temp_y * math.cos(angle)
```

I think it improves readability and may significantly improve performance (AFAIK it removes 3 divides and 3 multiplies).

**Comment by humansHS** [comment]
Actually even better:

```
    # now apply rotation
    angle = math.radians(angle)
    cos_angle = math.cos(angle)
    sin_angle = math.sin(angle)
    rotated_x = temp_x * cos_angle - temp_y * sin_angle
    rotated_y = temp_x * sin_angle + temp_y * cos_angle
```

I believe 1/4 the calls to radians() and 1/2 the calls to cos() and sin() will significantly improve rotate_point performance.

**Comment by pvcraven** [comment]
I don't know how/where this lines up with the current code.

Paul Vincent Craven

**Comment by humansHS** [comment]
> https://youtu.be/rNqCxrY94q0

I literally have no idea why that is happening... It makes no sense to me that relative is working but absolute is not :confounded: ... I am fairly certain absolute WAS working before. My only possible guess is that it has to do with the small angle change and small offset distance, so rounding errors are going haywire? But that seems unlikely :confused: 

> I don't know how/where this lines up with the current code.

It is in drawing_support.py around line 105 (function rotate_point starts at line 88). The function rotate_point gets called in A LOT of different processes, and I believe cos/sin calls can be quite costly, so for anything that results in lots of rotating this should be a good change.

I have submitted a pull request but I do not believe it will fix the absolute issue, it is just code tweaks. #592

**Comment by pvcraven** [comment]
Ok, after spending a few hours on it this morning, I've come to the conclusion this is way, way more complex than I originally thought it would be. 

Currently there's a center_x, center_y. 

If we want to track an offset there needs to be a origin_x, origin_y, distance, angle. Center_x, center_y would be calculated from that.

See: https://arcade.academy/examples/sprite_collect_coins_move_circle.html#sprite-collect-coins-move-circle

It could use a spec document that's gone over with a fine-toothed comb before coding. Or start with tests, and then code.

**Comment by pvcraven** [comment]
And if we track extra variables around movement, we have to make sure performance doesn't take a hit. I'm going to remove this code for now. I'm still interested in implementing it, but it will require some careful thought. I'd recommend coding a super-simple proof of concept that involves no graphics at all. Just get the numbers right. Then apply that to Arcade.

**Comment by humansHS** [comment]
I agree.

I have implemented the system in the code for my game and it is literally only 5 simple lines BUT I think that is because it is a very specific case.

I have sprites (in my case weapons) that are 'attached' to another sprite (the player). The 'weapons' have their centre_x and centre_y updated whenever the 'player' center_x and center_y is changed. The 'weapons' have an offset that is applied to the center_x/y adjustment. They also have their rotation updated whenever the player rotation changes, but they also have their center_x/y rotated. It works well, and once sprite.draw() is fixed I'll record it :smiley: 

As you said we have to track variables and make sure that it doesn't hit performance. AFAIK Python variable writing and comparisons are relatively quick. I am fairly new to GitHub and shared projects so I have been struggling with proper testing of the code I have been submitting. I'll do some thorough work before submitting anything here!

**Comment by pvcraven** [comment]
It is reasonably quick, but I'm trying for the best performance with thousands of moving sprites. Updating variables takes a noticeable amount of time when moving 3000 sprites 60 times per second.

Anyway, shame it opened a can of worms. I had no idea it was going to be that complex!

**Comment by pvcraven** [comment]
Closing.
