### ISSUE TITLE
Primitive draw functions optimization (?)

### ISSUE THREAD

**Issue by MrGallo** [pvcraven/arcade#595]
Are there any plans (or impediments) to handle primitive draw functions (e.g., `arcade.draw_circle`) the way `arcade.draw_text` is handled? Create a cache and a shape sprite and use those to draw, rather than reconstructing the shape each `on_draw` iteration?

**Comment by pvcraven** [comment]
No plans. Seems like it would be possible though.

**Comment by MrGallo** [comment]
I'm having difficulty understanding https://github.com/pvcraven/arcade/blob/90630926eb3f181c511143a105217962370e61bb/arcade/draw_commands.py#L395 
It takes the shape as points, and then evaporates into the air. How would one take the generated shape and stick it into a texture (to be able to cache and put in a `shape_sprite`)?

The `draw_text` function uses PIL.
https://github.com/pvcraven/arcade/blob/90630926eb3f181c511143a105217962370e61bb/arcade/text.py#L215-L228

Would that mean we would now have to draw shapes using PIL, or can we derive a `PIL.Image` from the `_generic_draw_line_strip` function?

**Comment by pvcraven** [comment]
Textures and PIL have nothing to do with the primitive shape drawing. 

Drawing involves creating a bunch of points and drawing triangles between them. In the case of sprites/text we pop an image on the triangle. In the case of drawing primitives, we just set colors.

You can take a look at the ShapeElementList to get an idea how it is done. If fact, you might be able to use that code.

**Comment by pvcraven** [comment]
Putting this on the enhancement list, and closing.

**Comment by einarf** [comment]
@MrGallo Just to keep you updated. I think this issue is already solved.

The draw functions have been heavily optimized since this issue was created. Most of them are fast enough to not need any caching now. We generate the gemoetry on the fly with a geometry shader.

Text is also no longer cached since we switched to pyglet text. This caching caused so many issues I don't really know where to start. A slightly faster alternative to `draw_text` is the `Text` object, but this is not needed in most cases.

Buffered shapes still need a lot of work though, but they are more than ok for  static things.
