### ISSUE TITLE
[help] Disable warping on platform collision

### ISSUE THREAD

**Issue by dzervas** [pvcraven/arcade#89]
I'm trying to stop warping while colliding on the left/right edge of a platform (try to start falling on the edge on the platform and then press the opposite X key. ex. if you are on the left edge of a platform press right) in the physics engine. How can I achieve that?

I'll make a new physics class that inherits PhysicsEnginePlatformer

**Comment by Avidhero** [comment]
I too experience this issue. Just running the tiled-map example and pressing left causes the player to "spider" the boxes till he warps on top of them. Problem with the physics platformer engine.

Would love a fix as am trying to use arcade to demo some class room ideas.

**Comment by dzervas** [comment]
After extensive though, I couldn't seem to find a fix...

**Comment by pvcraven** [comment]
Just today, I was finally able to reproduce based on some code I was sent. It has to do with rounding errors and how computers handle floating point numbers. Fix is currently being worked on.

**Comment by pvcraven** [comment]
A new version has been deployed. Try updating arcade and see if the issue is fixed. Should be "pip install --update arcade" or pip3 if you are on mac/linux.

**Comment by Avidhero** [comment]
Thank you for looking into this. After update (pip install update arcade) to 0.4.4, spider behavior still exist when pressing left against wall on tiled example code  (Version 1.0.1.post1 according to pip show arcade).

Still not fixed for me.

**Comment by pvcraven** [comment]
That's not the new version. Did you put two dashes in front of the
"upgrade"? Or try uninstalling and reinstalling. I think it should show
post 6 or something like that.

**Comment by Avidhero** [comment]
Thank you, I have just reinstalled arcade to insure newest version (no such option: --update)
Installing collected packages: arcade
Successfully installed arcade-1.0.1.post6

Same problem with the spider effect when pressing left.
Still not fixed.


Windows 7 Enterprise SP1 (64-bit)
Python 3.6 (32-bit)
Dual Xeon CPU

**Comment by pvcraven** [comment]
Ok, post6 is the correct version. Very interesting that it isn't working.
Any chance you can send sample code?

Paul Vincent Craven

**Comment by Avidhero** [comment]
http://pythonhosted.org/arcade/examples/sprite_tiled_map.html
Run this code, press left. Player spiders up boxes. Jump and press left and player can climb extremely high walls.
[tiled..txt](https://github.com/pvcraven/arcade/files/841864/tiled.txt)


The first thing I notice in the platformer engine though is this :
 ` elif self.player_sprite.change_y < 0:
                for item in hit_list:
                    while check_for_collision(self.player_sprite, item):
                        self.player_sprite.bottom += 0.5`
Since gravity is always in affect, if an input is holding for a direction without a Y input... against a wall for example, we will have a collision before the X sides are aligned. So, we will float up until no more collision. Problem is, the X collision is never resolved (until we float above the collision object).

Hope that helped.

**Comment by pvcraven** [comment]
Issue #89 and Issue #110 are different issues, with similar results.

**Comment by pvcraven** [comment]
Please try Version 1.0.1 post 7. Thank you!
